In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# *****NDArray Oluşturma**

In [2]:
import numpy as np
x = np.array([4,5,6,7])
print(x)

[4 5 6 7]


#  x in türünü bulma, class ı yazdırma

In [3]:
print(type(x))

<class 'numpy.ndarray'>


# Eksendeki eleman sayısını tuple olarak yazma

In [4]:
print(x.shape)

(4,)


# Eleman sayısını yazma

In [5]:
print(x.size)

4


# Boyutu yazma

In [6]:
print(x.ndim)

1


# Veriyi depolamak için kullanılan byte ı yazma

In [7]:
print(x.nbytes)

32


# x in veri tipini yazma

In [8]:
print(x.dtype)

int64


**-------------------------------------**2 Boytlu  **-------------------------------------**

In [9]:
y = np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [10]:
print(type(y))
print(y.shape)
print(y.size)
print(y.ndim)
print(y.nbytes)
print(y.dtype)

<class 'numpy.ndarray'>
(2, 3)
6
2
48
int64


* (type(y)) --> class yazma
* (y.shape) --> (satır,sütun) yazar
* (y.size) --> eleman sayısını yazar
* (y.ndim) --> satır ve sütundan oluştuğu için 2 yazar
* (y.nbytes) --> hafızadaki tuttuğu byte yazar
* (y.dtype) --> verilerin tipini yazar

**-------------------------------------**3 Boytlu  **-------------------------------------**

In [11]:
z = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(z)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [12]:
print(z.shape)
print(z.ndim)

(2, 2, 2)
3


* (z.shape) --> 2 tane 2x2 matris varmış gibi düşünülebilir.
* (z.ndim) --> boyutu yazar

# *****Veri Tipleri**

# Veri tipi değiştirme-1

In [13]:
import numpy as np
x  = np.array([3,4,5],dtype = np.float16)
print(x.dtype)

float16


In [14]:
x = np.array([1.0,2,3,4],dtype=np.int32)
print(x.dtype)

int32


# Veri tipi değiştirme-2

In [15]:
x = np.array([1,2,3,4])
x = x.astype(np.float16)
print(x.dtype)

float16


In [16]:
y = np.array([1.2, 2,5])
y = y.astype(np.int16)
print(y.dtype)

int16


# -----------------------------------------------

# np.zeros() ve np.ones()

In [17]:
x = np.zeros(4)
print(x)

[0. 0. 0. 0.]


In [18]:
y =np.ones(4)
print(y)
print(y.dtype)

[1. 1. 1. 1.]
float64


In [19]:
x1= np.zeros((3,2))
print(x1)
print(x1.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64


In [20]:
x1 = np.zeros((3,2), dtype = np.int32)
print(x1)

[[0 0]
 [0 0]
 [0 0]]


In [21]:
x2 = np.ones((3,2,2), dtype = np.int16)
print(x2)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [22]:
x = np.ones((2,3)) * 10.0
print(x)

[[10. 10. 10.]
 [10. 10. 10.]]


In [23]:
y = np.zeros((2,3)) * 10.0
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


# np.full()

In [24]:
x = np.full((3,2), 10)
print(x)

[[10 10]
 [10 10]
 [10 10]]


* 3 e 2 lik matriste ki elemanlrın hepsini 10 yazar

In [25]:
x = np.full((3,2), 10)
print(x.dtype)

int64


* dtype ı int çünkü 10 integer sayıdır.

In [26]:
x = np.full((3,2), 10)
print(x)

[[10 10]
 [10 10]
 [10 10]]


# np.empty() ve .full()

In [27]:
y = np.empty((2,2))
print(y)

y.fill(5) # fill()ise rastgele doldurulan yerlere hangi sayıyı istersen ona göre dolduruyor.
print(y)

[[1. 1.]
 [1. 1.]]
[[5. 5.]
 [5. 5.]]


* np.empty() rastgele sayılarla doldurur
* .fill() ise rastgele yerlere parametre içindeki sayıları yazar

# 1-Birim matris yapma, np.eye()

In [28]:
x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
y =np.eye(5,4)
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


* genelde eye() (4,4), (5,5) gibi matrisler için kullanılır.

In [30]:
x = np.eye(6)
print(x)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [31]:
x = np.eye(6,k=1)
print(x)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


* 1 ler bir birim yukarıdan başladı

In [32]:
x = np.eye(6,k = -2)
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


* 1 ler 2 birim aşağıdan başladı

# 2- Birim matris yapma, np.identity()

In [33]:
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# np.diag()

In [34]:
x = np.diag([2,4,6,8])
print(x)

[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]


* Yazılan sayıalr liste halinde yazılır ve onlarda köşegene yazılır.

# **------------------------- --------------------------**

# np.arange()

In [35]:
x = np.arange(4)
print(x)

[0 1 2 3]


* 4 dahil değildir.

In [36]:
y = np.arange(4,9)
print(y)

[4 5 6 7 8]


* 9 dahil değildir

In [37]:
z = np.arange(3,23,4)
print(z)

[ 3  7 11 15 19]


* 3 den 21e dörder dörder yazar.fakat 23 ü yazmaz

# np.linspace()

In [38]:
x = np.linspace(1,10,5)
print(x)

[ 1.    3.25  5.5   7.75 10.  ]


* 1den 10a kadar 5 tane sayı yazar,fakat bunda 10 dahildir.

In [39]:
y = np.linspace(1,10)
print(y)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


* diyelimki 3. parametreyi yazmadık o zaman otamatik olarak 50 kabul edilir.

In [40]:
z = np.linspace(1,10,endpoint=False)
print(z)

[1.   1.18 1.36 1.54 1.72 1.9  2.08 2.26 2.44 2.62 2.8  2.98 3.16 3.34
 3.52 3.7  3.88 4.06 4.24 4.42 4.6  4.78 4.96 5.14 5.32 5.5  5.68 5.86
 6.04 6.22 6.4  6.58 6.76 6.94 7.12 7.3  7.48 7.66 7.84 8.02 8.2  8.38
 8.56 8.74 8.92 9.1  9.28 9.46 9.64 9.82]


* Diyelimki en son aralıktaki sayıyı almak istemiyoruz. Yani 10u almak istemiyoruz ozaman 3. parametre olarak endpoint = False yazılır.

# np.reshepe()

In [41]:
x = np.arange(1,21)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [42]:
y = np.reshape(x,(4,5))
print(y)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


* Tek boyutlu olan x i, iki boyutlu (4,5) matrisi yaptık

In [43]:
z = np.reshape(x ,(5,2,2))
print(z)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


* Tek boyutlu olan x i, 3 boyutlu matris yaptık

# Tek Satırda Yazma

In [44]:
x = np.linspace(0,19,20)
print(x)
y = np.reshape(x,(2,10))
print(y)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


* Burada yaptığımızı tek satırda da yapabilirz.

In [45]:
x = np.linspace(0,19,20).reshape(2,10)
print(x)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


# np.random.random()

In [46]:
x = np.random.random((2,3))
print(x)

[[0.81362325 0.62027654 0.73022426]
 [0.7199821  0.09804442 0.54999665]]


* Burada 2 satıra 3 sütunluk matris oluşur fakat elemanları rastgele oluşur. Bu elemanlar 0 ile 1 arasındadır,fakat 1 dahil değildir.

# np.random.randint()

In [47]:
x = np.random.randint(3,12, size= (3,2))
print(x)

[[11  7]
 [ 7  6]
 [ 3  7]]


* 3 ve 12 arasındaki tam sayıları rastgele alır ve (3,2)lik matrisi yazdırır.

# **------------------------ -------------------------**

# tek boyutuda index numarası

In [48]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [49]:
print(x[0])

0


In [50]:
print(x[2])

2


In [51]:
print(x[-1])

4


#  tek boyutuda indexteki elemanı değiştirme

In [52]:
x = np.arange(5)
x[2]= 200
print(x)

[  0   1 200   3   4]


* x in 2.indexindeki eleman 200 oldu

# np.delete() Tek boyutuda index silme 

In [53]:
x = np.arange(6)
print(x)
x = np.delete(x,[0,1])
print(x)

[0 1 2 3 4 5]
[2 3 4 5]


* silme işlemi için np.delete() i kullandık ve içine parametre olarak x in 0 ve 1. indexindeki elemanlrını sil dedik

# append() Tek Boyutluda Eleman Ekleme

In [54]:
x = np.arange(5)
print(x)
print("--------------")
x = np.append(x, [100])
print(x)
print("---------------")
x = np.append(x, [200,300])
print(x)

[0 1 2 3 4]
--------------
[  0   1   2   3   4 100]
---------------
[  0   1   2   3   4 100 200 300]


append() e ilk neye ekliyeceğimizi,ikiniciye ne ekliyeceğimizi yazıyoruz

# np.insert() ile Tek Boyutluda Eleman ekleme

* Bu metod ile heryere eleman eklenebilir,append de sona ekleme yapılıyordu.
* parametre olarak np.insert(neye eklicen, kaçıncı indekse eklicen,ne eklicen)

In [55]:
x = np.arange(5)
print(x)
x = np.insert(x,2,99)
print(x)

[0 1 2 3 4]
[ 0  1 99  2  3  4]


* x in 2. indexinin olduğu yere 99 sayısını ekler.

# 2 boyutluda index bulma

In [56]:
x = np.arange(12).reshape((3,4))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [57]:
print(x[0,0])
print(x[1,3])

0
7


# 2 Boyutlda index değiştirme

In [58]:
x = np.arange(12).reshape((3,4))
print(x)
print("--------")
x[0,0] = 100
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


# 2 Boyutluda Eleman Silme axis = 0 --> satır(row), axis = 1--> sütun(column

In [59]:
x = np.arange(16).reshape(4,4)
print(x)
print("----------")
x = np.delete(x, [1], axis = 0)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


* 2 bouytluda bi parametre daha ekliyoruz o da axis parametresi 10 ise satır,sütın ise 1 yazılır.

# append() 2 Boyutluda Satıra Eleman Ekleme

In [60]:
x = np.arange(9).reshape(3,3)
print(x)
print("---------")
x = np.append(x, [[100,200,300]],axis = 0)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
---------
[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [100 200 300]]


# np.append() 2 Boyutluda Sütuna Eleman Ekleme

In [61]:
x = np.arange(12).reshape(4,3)
print(x)
print("---------")
x = np.append(x, [[10],[20],[30],[40]], axis = 1)
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
---------
[[ 0  1  2 10]
 [ 3  4  5 20]
 [ 6  7  8 30]
 [ 9 10 11 40]]


* Sütuna eleman eklerken tek tek liste halinde eklenir.Çünkü her satıra ayrı eleman ekleniyor.Fakat satır eklerken tek bir liste ekeleniyor.

# np.insert() ile 2 Boyutluda Eleman Ekleme

In [62]:
x = np.arange(9).reshape(3,3)
print(x)
x = np.insert(x,[0,0],[ 10,11,12], axis =0)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [10 11 12]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [63]:
x = np.arange(9).reshape(3,3)
print(x)
print("-----------")
x = np.insert(x, [3], [77] ,axis = 0)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-----------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [77 77 77]]


In [64]:
x = np.arange(9).reshape(3,3)
print(x)
print("-------------")
x = np.insert(x, [1], [99,88,77], axis =0)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------
[[ 0  1  2]
 [99 88 77]
 [ 3  4  5]
 [ 6  7  8]]


In [65]:
x = np.arange(9).reshape(3,3)
print(x)
print("------------")
x = np.insert(x, 0 ,[10,20,30], axis = 1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------
[[10  0  1  2]
 [20  3  4  5]
 [30  6  7  8]]


# np.stack()

> **1 --> np.vstack() --> vertical stack yani dikey iliştrme**

In [66]:
x = np.arange(3)
print(x)
print("--------")
y = np.arange(9).reshape(3,3)
print(y)
print("---------")
z = np.vstack((x,y))
print(z)

[0 1 2]
--------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
---------
[[0 1 2]
 [0 1 2]
 [3 4 5]
 [6 7 8]]


* x i y nin üzerine yazar

> **2 --> np.hstack() --> hortizontal stack yani yatay iliştrme**

In [67]:
x = np.arange(3)
print(x)
print("--------")
y = np.arange(9).reshape(9,)
print(y)
print("---------")
z = np.hstack((x,y))
print(z)

[0 1 2]
--------
[0 1 2 3 4 5 6 7 8]
---------
[0 1 2 0 1 2 3 4 5 6 7 8]


* Boyutlarının aynı olamsı lazım o yüzden reshape(9,) yaptık.

# **-------------------------- --------------------------**

# slicing yani ndArray in alt kümesine ulaşma Tek Boyutluda

In [68]:
x = np.arange(10)
print(x)
print("------")
print(x[2:6]) # 2den 6. elemana kadar yazar. 6 dahil değil
print("------")
print(x[4:])#4 ten en sona kadar yazar.
print("------")
print(x[:7])#en baştan 7.elemana kadar yazar. 7 dahil değil

[0 1 2 3 4 5 6 7 8 9]
------
[2 3 4 5]
------
[4 5 6 7 8 9]
------
[0 1 2 3 4 5 6]


In [69]:
x = np.arange(10)
print(x)
print("------")
print(x[:-1]) # -1 demek son eleman demek, son elemanı yazmaz.
print("------")
print(x[-4:-2])

[0 1 2 3 4 5 6 7 8 9]
------
[0 1 2 3 4 5 6 7 8]
------
[6 7]


# slicing yani ndArray in alt kümesine ulaşma 2 Boyutluda

In [70]:
x = np.arange(25).reshape(5,5)
print(x)
print("--------")
y = x[0:3, 1:4] #0 1 2. satırın , 1 2 3. sütunu yazar
print(y)
print("--------")
z = x[2:]
print(z)# 2. satırdan başlayarak bütün satırları yazar
print("--------")
t = x[::]
print(t)# x matrisinin hepsini yazar
print("--------")
v = x[:, 3:]
print(v)#bütün satırların 3. sütunundan itibaren yazar.
print(np.may_share_memory(t,v))# t ve v nin sadece sayıları değişiyor,kapladığı yerler aynı

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
--------
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
--------
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
--------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
--------
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]
True


In [71]:
x = np.arange(9).reshape(3,3)
print(x)
x[0,0] = 100
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[100   1   2]
 [  3   4   5]
 [  6   7   8]]


# copy()

In [72]:
x = np.arange(16).reshape(4,4)
print(x)
print("---------")
y = np.copy(x[0:3, 1:3])
print(y)
print(np.shares_memory(x,y))#slicing gibi kapladığı yer aynı değil. np.copy() nin tuttuğu yerde farklıdır.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
---------
[[ 1  2]
 [ 5  6]
 [ 9 10]]
False


# 2 slicing

In [73]:
x = np.linspace(1,21,11)
print(x)
print("------")
y = np.array([2,4,7])
print(y)
print("------")
print(x[y])#  y deki 2. 4. ve 7. indexleri yazar

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
------
[2 4 7]
------
[ 5.  9. 15.]
